# -*- coding: utf-8 -*-
"""Desafio-sono.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18-hD7bdBeP5b1O9ki7Mkni23kiOjYrZJ
"""

pip install pandas

import pandas as pd

url = "https://raw.githubusercontent.com/CristianaMoura/Desafio-Sono-DadosWomakersCode/refs/heads/main/saude_do_sono_estilo_vida.csv.csv"
df = pd.read_csv(url)
df.head(10)  # Exibe as primeiras linhas

"""1. Ao visualizar a base você percebeu que seria melhor alterar o nome de algumas colunas. Mude o ‘ID’ para ‘Identificador’, corrija o nome da coluna que indica a pressão sanguínea, mude a coluna ‘Ocupação’ para ‘Profissão’,a coluna ‘Categoria BMI’ está em parte em inglês, substitua para ‘Categoria IMC’.

"""

df = df.rename(columns={'ID': 'Identificador', 'Pressão sanguíneaaaa': 'Pressão sanguínea', 'Ocupação': 'Profissão', 'Categoria BMI': 'Categoria IMC'})
df.head()

##2. Qual é a média, a moda e a mediana de horas de sono para cada uma
##das profissões? [‘mean’, np.median, pd.Series.mode]


df.groupby('Profissão')['Duração do sono'].agg(['mean', 'median', pd.Series.mode])


##3. Das pessoas que atuam com engenharia de software qual a
##porcentagem de obesos?

porcentagem_obesos = (
    (df[(df['Profissão'] == 'Eng. de Software') & (df['Categoria IMC'] == 'Obesidade')].shape[0]) /
    (df[df['Profissão'] == 'Eng. de Software'].shape[0]) * 100
)

print(f"Porcentagem de engenheiros de software obesos: {porcentagem_obesos:.2f}%")


##4. De acordo com os dados, advogar ou ser representante de vendas faz
##você dormir menos? (Use o método ‘isin’, considere a média)

horas_sono = df[df['Profissão'].isin(['Advogado', 'Representante de Vendas'])]['Duração do sono']
media_horas_sono = horas_sono.mean()
print(f"Média de horas de sono para advogados e representantes de vendas: {media_horas_sono:.2f}")

##5. Entre quem fez enfermagem e quem fez medicina, quem tem menos
##horas de sono? (Use o método ‘isin’, considere a média)

menos_horas_sono = df[df['Profissão'].isin(['Enfermagem', 'Medicina'])]['Duração do sono']
media_menos_horas_sono = menos_horas_sono.mean()
print(f"Média de horas de sono para enfermeiros e médicos: {media_menos_horas_sono:.2f}")

##6. Faça um subconjunto com as colunas Identificador, Gênero, Idade,
##Pressão sanguínea e Frequência cardíaca.

subconjunto = df[["Identificador", "Gênero", "Idade", "Pressão sanguínea", "Frequência cardíaca"]]
print(subconjunto.head())

##7. Descubra qual a profissão menos frequente no conjunto. (Use
##value_counts)

menos_frequente = df['Profissão'].value_counts().idxmin()
print(f"A profissão menos frequente é: {menos_frequente}")

##8. Quem tem maior pressão sanguínea média, homens ou mulheres?
##(Considere a média)

df["Pressão Sistólica"] = df["Pressão sanguínea"].str.split('/').str[0].astype(float)
media_pressao = df.groupby("Gênero")["Pressão Sistólica"].mean()

print(media_pressao)

##9. É predominante entre os participantes dormir 8 horas por dia
##(considere usar Moda como medida)?


moda = df['Duração do sono'].mode()[0]
print(f"A moda é: {moda}")

##10. Pessoas com frequências cardíacas acima de 70 dão mais passos que
##pessoas com frequência cardíaca menor ou igual a 70? (Use a média)


frequencia_maior = df[df['Frequência cardíaca'] > 70]['Passos diários'].mean()
frequencia_menor = df[df['Frequência cardíaca'] <= 70]['Passos diários'].mean()
media_frequencia = frequencia_maior - frequencia_menor

print(f"Em média, pessoas com frequência cardíaca acima de 70 dão {media_frequencia:.2f} passos a mais")